# Page settings

baseURL = "https://wakinchan.work/"
languageCode = "ja"
title = "ğŸ¥¬ğŸ¥¬ğŸ¥¬ This is YUSUKE :)"
theme = "devresume"
googleAnalytics = "UA-39033033-3"

[params]
    author = "Yusuke KUROIWA"
    description = "Hello. This is YUSUKE :)"
    primaryColor = "#007042"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Yusuke KUROIWA"
        tagline = "Software Engineer"
        avatar = "wakinchan-memoji-black.png"

    [params.contact]
        enable = true
        location = "Meguro, Tokyo, JAPAN"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:08046499618"
        text = "080-4649-9618"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:kinda.dev@gmail.com"
        text = "kinda.dev(at)gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "wakinchan.work"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "Closed (kindadev.com)"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Swift/Objective-C/Xcode"
        [[params.skills.list.items]]
        details = "RxSwift/ReactiveCocoa"
        [[params.skills.list.items]]
        details = "React/TypeScript/WebStorm"
        [[params.skills.list.items]]
        details = "GoLang/gPRC/Protocol Buffers"
        [[params.skills.list.items]]
        details = "MVC/MVP/MVVM/Redux"
        [[params.skills.list.items]]
        details = "Bitrise/CircleCI/Fastlane"
        [[params.skills.list.items]]
        details = "AWS/GCP/Firebase"
        [[params.skills.list.items]]
        details = "CI/CD"
        [[params.skills.list.items]]
        details = "Sketch/Figma"
        [[params.skills.list.items]]
        details = "Apple DEP/VPP/MDM/Apple Configurator"
        [[params.skills.list.items]]
        details = "Wordpress"

        [[params.skills.list]]
        title = "Others"
        [[params.skills.list.items]]
        details = "Scrum"
        [[params.skills.list.items]]
        details = "Design and implement software systems"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Hacking iOS and other apps"
        [[params.skills.list.items]]
        details = "DOOM II"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "å¤§é˜ªå·¥æ¥­å¤§å­¦"
        university = "ã‚³ãƒ³ãƒ”ãƒ¥ãƒ¼ã‚¿ç§‘å­¦ç§‘"
        dates = "2010 - 2014"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "try! Swift Tokyo 2017 hackathon freeeè³"
        body = "Multipeer Translation iOS application"
        date = "2017.03.04"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Japanese"
        level = "Native"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "ã‚¬ã‚¸ã‚§ãƒƒãƒˆ"
        [[params.interests.list]]
        name = "ãƒ†ã‚¯ãƒãƒ­ã‚¸ãƒ¼"
        [[params.interests.list]]
        name = "æ±ºæ¸ˆ"
        [[params.interests.list]]
        name = "æ¤ç‰© / æ¸©å®¤"
        [[params.interests.list]]
        name = "æ—…è¡Œ"
        [[params.interests.list]]
        name = "ãƒ¢ãƒ“ãƒªãƒ†ã‚£"
        [[params.interests.list]]
        name = "Emoji ğŸŒµ"

    [params.summary]
        enable = true
        text = "Yusuke KUROIWA (é»’å²© è£•è¼”), 1992å¹´, ç¥æˆ¸ç”Ÿã¾ã‚Œ, 28æ­³ã€‚\n\nå¤§å­¦ç”Ÿã®ã¨ãã«ã€å€‹äººãƒ–ãƒ­ã‚°ã€Œãã‚“ã¡ã‚ƒã‚“ã¶ã‚ãã€ã‚’ç«‹ã¡ä¸Šã’ã€iOS Jailbreak Communityã§iOSã®ç ”ç©¶ãƒ»Jailbreak Tweak Appé–‹ç™ºã‚’è¶£å‘³ã§ã—ã¦ã„ãŸã€‚ãƒ–ãƒ­ã‚°ã¯æœˆé–“100ä¸‡ãƒ“ãƒ¥ãƒ¼ã‚’è¶…ãˆã‚‹ï¼ˆ2020å¹´ã«ã‚ãŸã‚‰ã—ã„ã“ã¨ã‚’ã—ãŸãé–‰é–ï¼‰ã€‚\n\næ–°å’ã§åœ°å…ƒç¥æˆ¸ã®ä¼šç¤¾ã«å…¥ç¤¾ã€Android OSã®Camera HALã®å®Ÿè£…ã«æºã‚ã‚‹ã€‚\n\niOSã«æºã‚ã‚ŠãŸãã€Twitterã§èª˜ã£ã¦ã„ãŸã ã„ã¦ãŸã€æ±æ€¥ãƒãƒ³ã‚ºã®æƒ…ã‚·ã‚¹ã®ä¼šç¤¾ãƒãƒ³ã‚ºãƒ©ãƒœã¸è»¢è·ã€ä¸Šäº¬ã€‚è‡ªç¤¾ãƒ¬ã‚¸ã®ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆç«‹ã¡ä¸Šã’ã‚’æ‹…ã†ã€‚ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆãƒªãƒ¼ãƒ€ãƒ¼ã¨ã—ã¦ã€POSæ©Ÿèƒ½ã®é–‹ç™ºå¼·åŒ–ãƒ»åº—èˆ—ã¸ã®è¨­ç½®å°å…¥ãƒ»é‹ç”¨ãƒ»å–å¼•å…ˆã¨ã®èª¿æ•´ãƒ»æ¡ç”¨ãªã©ã‚ã‚‰ã‚†ã‚‹ã“ã¨ã‚’è¡Œã£ãŸã€‚\næ–°è¦äº‹æ¥­ç«‹ã¡ä¸Šã’ã®ã‚½ã‚¦ã‚¾ã‚¦(ãƒ¡ãƒ«ã‚«ãƒª)ã«å…¥ç¤¾ã€‚ã‚·ã‚§ã‚¢ã‚µã‚¤ã‚¯ãƒ«ã‚µãƒ¼ãƒ“ã‚¹ã®ãƒ¡ãƒ«ãƒãƒ£ãƒªã®ã‚µãƒ¼ãƒ“ã‚¹ç«‹ã¡ä¸Šã’ã‚’æ‹…ã†ã€‚ä¸¦è¡Œã—ã¦ãƒ¡ãƒ«ãƒãƒ£ãƒªã®é‹ç”¨ã«é–¢é€£ã™ã‚‹Webã‚„ã€ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰ã®é–‹ç™ºã®ä¸€éƒ¨ã‚‚ä¸€ç·’ã«è¡Œã£ãŸã€‚ãã®å¾Œã€ãƒ•ã‚¡ãƒƒã‚·ãƒ§ãƒ³ã®UXæ”¹å–„ã€ã‚°ãƒ­ãƒ¼ã‚¹ã«æºã‚ã£ã¦ã„ã‚‹ã€‚ã¾ãŸã€ãƒ†ãƒƒã‚¯ãƒªãƒ¼ãƒ‰ã¨ã—ã¦ã€ARKitã‚’ä½¿ç”¨ã—ãŸPOCã‚’é–‹ç™ºã‚’è¡Œã£ãŸã€‚ "

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2020.02 - Present"
        company = "Mercari, Inc."
        details = "ãƒ¡ãƒ«ã‚«ãƒªã®ãƒ•ã‚¡ãƒƒã‚·ãƒ§ãƒ³UXæ”¹å–„ã€ã‚°ãƒ­ãƒ¼ã‚¹ã‚’è¡Œã†ã€‚ãƒ•ã‚¡ãƒƒã‚·ãƒ§ãƒ³ã‚«ãƒ†ã‚´ãƒªã®UXæ”¹å–„ / ã‚°ãƒ­ãƒ¼ã‚¹ã«æºã‚ã‚‹ã€‚ãƒ†ãƒƒã‚¯ãƒªãƒ¼ãƒ‰ã‚’åŠªã‚ã€[ARKitã‚’ä½¿ã£ãŸT-shirtã®è‡ªå‹•æ¡å¯¸ã®POCé–‹ç™º](https://engineering.mercari.com/en/blog/entry/2020-06-19-150222/)ãªã©ã‚’è¡Œã†ã€‚ãã®å¾Œã‚‚iOSã‚’ãƒ¡ã‚¤ãƒ³ã¨ã—ã¤ã¤ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰ã«æºã‚ã‚‹ã€‚\n\nãƒ¡ãƒ³ãƒãƒ¼5-10å, iOS 10-14, Swift 4, MicroViewController, ReactiveSwift, MVVM, Redux, Microservice, GoLang"

        [[params.experience.list]]
        dates = "2018.02 - 2020.01"
        company = "Mercari, Souzoh, neuet.Inc."
        details = "ã‚½ã‚¦ã‚¾ã‚¦(ãƒ¡ãƒ«ã‚«ãƒª)ã«å…¥ç¤¾ã€‚ã‚½ãƒªãƒ¥ãƒ¼ã‚·ãƒ§ãƒ³ãƒãƒ¼ãƒ ã‹ã‚‰æ–°è¦äº‹æ¥­ã®[ã‚·ã‚§ã‚¢ã‚µã‚¤ã‚¯ãƒ«ã‚µãƒ¼ãƒ“ã‚¹ã€Œãƒ¡ãƒ«ãƒãƒ£ãƒªã€](https://charichari.bike/)äº‹æ¥­ã®ç«‹ã¡ä¸Šã’ã«æºã‚ã‚Šã€ç¦å²¡ã«ã¦ãƒªãƒªãƒ¼ã‚¹ã€‚iOSé–‹ç™ºã‚’ãƒ¡ã‚¤ãƒ³ã¨ã—ã¦æºã‚ã‚Šã€CSãƒ„ãƒ¼ãƒ«ã‚„ã€é‹ç”¨ã®ã‚¢ãƒ—ãƒªã®Webé–‹ç™ºã€å¿…è¦ã«å¿œã˜ã¦Backendã®é–‹ç™ºã‚‚ãŠã“ãªã£ãŸã€‚ç¬¬2ä¸–ä»£ã®éµé–‹ç™ºã™ã‚‹ãŸã‚ã€ä¸­å›½ã«ã¦éµã®ä»•æ§˜è¨­è¨ˆãªã©ã‚‚è¡Œã£ãŸã€‚\n\nãƒ¡ãƒ³ãƒãƒ¼10å, iOS 10-13, Swift 3-4, RxSwift, MVVM, TypeScript, React, GCP(AppEngine, Datastore), Firebase, GoLang, Hardware, CoreBluetooh"
        [[params.experience.list.items]]
        details = "ãƒ¡ãƒ«ãƒãƒ£ãƒªiOSã‚¢ãƒ—ãƒªã®è¨­è¨ˆãƒ»é–‹ç™º"
        [[params.experience.list.items]]
        details = "CSãƒ„ãƒ¼ãƒ«, é‹å–¶ã‚¢ãƒ—ãƒª, LPã®Webãƒ•ãƒ­ãƒ³ãƒˆã‚¨ãƒ³ãƒ‰ã®è¨­è¨ˆãƒ»é–‹ç™º"
        [[params.experience.list.items]]
        details = "2019.07.26 Â· ã€Œãƒ¡ãƒ«ãƒãƒ£ãƒªã€ã‚’äº‹æ¥­è­²æ¸¡ã™ã‚‹ãŸã‚ã€[neuet, Inc.](https://neuet.com/)ã‚’è¨­ç«‹ã«æºã‚ã‚Šã€å‡ºå‘"
        [[params.experience.list.items]]
        details = "2019.10 Â· ã‚ªãƒ•ã‚£ã‚¹ã®ç«‹ã¡ä¸Šã’ã«å¾“äº‹, ã‚ªãƒ•ã‚£ã‚¹ãƒ“ãƒ«æ¢ã—ã‹ã‚‰ãƒ‡ã‚¶ã‚¤ãƒ³, NWæ§‹ç¯‰ãªã©ã‚’æ‹…å½“"


        [[params.experience.list]]
        title = "IT Engineer"
        dates = "2015.03 - 2018.01"
        company = "HandsLab, Inc"
        details = "æ±æ€¥ãƒãƒ³ã‚ºã®POSãƒ¬ã‚¸ã‚’iPadã‚’ç”¨ã„ãŸPOSãƒ¬ã‚¸ã€ŒHandsPOSã€ã¸ã€ãƒªãƒ—ãƒ¬ãƒ¼ã‚¹ã™ã‚‹ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã‚’ã‚ªãƒ•ã‚¡ãƒ¼ã‚’ã•ã‚Œå…¥ç¤¾ã€‚ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã®ç«‹ã¡ä¸Šã’ã€è¦ä»¶å®šç¾©ã€è¨­è¨ˆã€é–‹ç™ºã€ãƒªãƒªãƒ¼ã‚¹ã€åº—èˆ—å±•é–‹ã€é‹ç”¨ã€å¤–éƒ¨äº¤æ¸‰ãªã©ã‚’è¡Œã£ãŸã€‚\n\nå…¥ç¤¾å½“åˆã¯iOSã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã¯ãŠã‚‰ãšã€iOSå´ã¯1äººã§POSåŸºæœ¬æ©Ÿèƒ½ã‹ã‚‰å¤–éƒ¨æ©Ÿå™¨é€£æºã¾ã§å®Ÿè£…ã€‚3äººã§(ãƒ‡ã‚¶ã‚¤ãƒŠãƒ¼1äºº, ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢1äºº)ã§9ãƒ¶æœˆã§åˆå›ã®ãƒªãƒªãƒ¼ã‚¹ã—ãŸã€‚2016å¹´9æœˆã‹ã‚‰ãƒãƒ¼ãƒ ãƒªãƒ¼ãƒ€ãƒ¼ã¨ã—ã¦å¾“äº‹ã€‚ãã®å¾Œã€ã‚¯ãƒ¬ã‚¸ãƒƒãƒˆç«¯æœ«é€£å‹•ã€é›»å­ãƒãƒãƒ¼ç«¯æœ«é€£æºã€ã‚»ãƒŸã‚»ãƒ«ãƒ•ãƒ¬ã‚¸å¯¾å¿œã€ã‚¤ãƒ³ãƒã‚¦ãƒ³ãƒ‰å‘ã‘æ±ºæ¸ˆå¯¾å¿œã¾ã§è¡Œã†ã€‚\n\næœ€å¤§ãƒ¡ãƒ³ãƒãƒ¼6å, iOS 8-10, Swift 1-3, AWS (Lambda, DyanmoDB, S3, SNS, Kinesis, Congnito), Unicage, Windows POS Ready 7, OPOS, UPOS"
        [[params.experience.list.items]]
        details = "POSåŸºæœ¬æ©Ÿèƒ½ (å£²ä¸Š, è¿”å“, å€¤å¼•ãƒ»å‰²å¼•, ãƒã‚¹ã‚¿ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰ ç­‰)é–‹ç™º"
        [[params.experience.list.items]]
        details = "å¤–éƒ¨æ©Ÿå™¨é€£æº (ãƒ¬ã‚·ãƒ¼ãƒˆãƒ—ãƒªãƒ³ã‚¿é€£å‹•, ã‚¹ã‚­ãƒ£ãƒŠé€£å‹•, è‡ªå‹•é‡£éŠ­æ©Ÿé€£å‹•) æ©Ÿèƒ½é–‹ç™º"
        [[params.experience.list.items]]
        details = "ãŠå®¢æ§˜å‘ã‘ãƒ‡ã‚£ã‚¹ãƒ—ãƒ¬ã‚¤(iPad) é€£æºæ©Ÿèƒ½é–‹ç™º"
        [[params.experience.list.items]]
        details = "é›»å­ãƒãƒãƒ¼æ±ºæ¸ˆæ©Ÿèƒ½é€£æºé–‹ç™º (äº¤é€šç³»ICã€Edyã€iDã€QUICPay), å¤–éƒ¨ãƒ™ãƒ³ãƒ€ãƒ¼èª¿æ•´, é›»å­ãƒãƒãƒ¼æ¤œå®šãƒ»è©¦é¨“å¯¾å¿œ"
        [[params.experience.list.items]]
        details = "ã‚¯ãƒ¬ã‚¸ãƒƒãƒˆæ±ºæ¸ˆæ©Ÿèƒ½é€£æºé–‹ç™º, ã‚·ãƒ³ã‚¯ãƒ©ã‚¤ã‚¢ãƒ³ãƒˆEMVå¯¾å¿œ"
        [[params.experience.list.items]]
        details = "POSã®åº—èˆ—å±•é–‹ / ãƒ¬ã‚¸å…¥æ›¿è¨­ç½® (ã‚­ãƒƒãƒ†ã‚£ãƒ³ã‚°ã‹ã‚‰LANé…ç·šã‚„ãƒ«ãƒ¼ã‚¿ã®è¨­ç½®ãªã©å«ã‚ã¦)"
        [[params.experience.list.items]]
        details = "å¤–éƒ¨èª¿æ•´ / é‹ç”¨å§”è¨—èª¿æ•´ / è¨­è¨ˆ"
        [[params.experience.list.items]]
        details = "MDM / DEPç®¡ç†æ–¹æ³•ã®æ¨é€² / èª¿æŸ», äº¤æ¸‰, é‹ç”¨æ–¹æ³•ç­–å®š, å°å…¥ / iPod touch å¾“æ¥­å“¡3,000äººåˆ†, iPad POS 800å°å‘ã‘"
        [[params.experience.list.items]]
        details = "ã‚»ãƒŸã‚»ãƒ«ãƒ•ãƒ¬ã‚¸è¨­è¨ˆ (ä¼šè¨ˆã‚’ãŠå®¢æ§˜ã«ã—ã¦é ‚ãå½¢æ…‹ã®æ©Ÿèƒ½è¿½åŠ )"
        [[params.experience.list.items]]
        details = "AliPay, WeChatPayè¨­è¨ˆ"
        [[params.experience.list.items]]
        details = "å¤–è²©å‘ã‘iOSã‚¢ãƒ—ãƒª, ç¤¾å†…å‘ã‘ã‚«ãƒ•ã‚§ãƒã‚¤ãƒ³ãƒˆã‚¢ãƒ—ãƒªã®ä½œæˆ (WKWebViewã‚¢ãƒ—ãƒª), Singapore POSã®ãƒã‚°æ”¹ä¿® (Objective-C), TokyuHandsPDAã®ãƒã‚°æ”¹ä¿®ãƒ»æ©Ÿèƒ½è¿½åŠ  (Objective-C)"


        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2014.06 - 2015.02"
        company = "æ±äº¬ã‚³ãƒ³ãƒ”ãƒ¥ãƒ¼ã‚¿ã‚µãƒ¼ãƒ“ã‚¹æ ªå¼ä¼šç¤¾"
        details = "Android Camera HAL moduleã®é–‹ç™º: è©³ç´°è¨­è¨ˆ, ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°, å˜ä½“ãƒ†ã‚¹ãƒˆ, çµåˆãƒ†ã‚¹ãƒˆ\n\nãƒ¡ãƒ³ãƒãƒ¼10å, Linux (Ubuntu), Android, AOSP, Qualcomm, C++, C, Java, Device Tree, Hardware, Prototype"


    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [params.information]
        enable = true
        [[params.information.list]]
        title = "Conference"
        [[params.information.list.items]]
        details = "2020.02.12 Â· potatotips #68, [æœªçŸ¥ã®ä¸–ç•Œ App Transfer](https://speakerdeck.com/wakinchan/wei-zhi-falseshi-jie-app-transfer-at-potatotips-number-68)"
        [[params.information.list.items]]
        details = "2017.09.17 Â· iOSDC Japan 2017, [iOSãƒ‡ãƒã‚¤ã‚¹3,500å°ã‚’ç®¡ç†ã™ã‚‹ã€ æ±æ€¥ãƒãƒ³ã‚ºã®ãƒ‡ãƒã‚¤ã‚¹æ‰‹æ³•ã¨ã¯](https://speakerdeck.com/wakinchan/iosdc-japan-2017-iosdebaisu3-500tai-woguan-li-suru-dong-ji-hanzufalsedebaisushou-fa-toha)"
        [[params.information.list.items]]
        details = "2017.03.11 Â· JAWSDAYS 2017 Lunch Session, [æ±æ€¥ãƒãƒ³ã‚ºã®iPad POSã€ŒHandsPOSã€ã¨ AWSã®ä»˜ãåˆã„æ–¹](https://www.slideshare.net/kindaiddqd/20170311-jawsdays-lunch-sessionipad-poshandspos-aws)"
        [[params.information.list.items]]
        details = "2016.08.20 Â· iOSDC Japan 2016 Lunch Session, [æ±æ€¥ãƒãƒ³ã‚ºã®POSã‹ã‚‰å­¦ã‚“ã ã€æ¥­å‹™iOSã‚¢ãƒ—ãƒªã®å‘ãåˆã„æ–¹](https://www.slideshare.net/kindaiddqd/20160820-iosdc-launch-sessionposios)"

        [[params.information.list]]
        title = "Blog"
        [[params.information.list.items]]
        details = """(Closed: 2012 - 2020) 2012å¹´å¤§å­¦ç”Ÿã®ã¨ãã«å§‹ã‚ãŸBlogã€Œãã‚“ã¡ã‚ƒã‚“ã¶ã‚ãã€
- å­¦ç”Ÿã®é ƒã€ä¸€æ™‚æœŸæœˆé–“100ä¸‡ãƒ“ãƒ¥ãƒ¼ã«åˆ°é”
- ä¸»ã«iOS è„±ç„ (Jailbreak) ã«é–¢é€£ã™ã‚‹è‡ªåˆ†ã§ä½œã£ãŸiOS Tweakã‚¢ãƒ—ãƒªã®ç´¹ä»‹ã€iOSã‚„macOSã®è§£æçµæœã€å®Ÿé¨“çµæœã€Tipsã«ã¤ã„ã¦æŠ•ç¨¿
- AWS EC2ã§Wordpressã‚’å‹•ã‹ã—ã¦é‹å–¶
        """

        [[params.information.list]]
        title = "Applications (a part)"
        [[params.information.list.items]]
        details = """2014 Â· ForceGoodFit / iOS Tweak: make older apps fit on your larger iPhone 6 and iPhone 6 Plus screen
- Cydia BigBoss repositoryã¸å…¬é–‹
- 23ä¸‡ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰
- [æµ·å¤–ã‚µã‚¤ãƒˆãƒ¬ãƒ“ãƒ¥ãƒ¼è¨˜äº‹](http://www.idownloadblog.com/2014/10/31/forcegoodfit-iphone-6-iphone-6-plus-resolution/), [ã‚«ã‚¦ãƒ³ã‚¿](http://apt.thebigboss.org/stats.php?dev=kindadev)
        """
        [[params.information.list.items]]
        details = """2014 Â· CCNowPlaying / iOS Tweak: Post #NowPlaying from Control Center
- Cydia BigBoss repositoryã¸å…¬é–‹
- 1ä¸‡7åƒãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰
- [æµ·å¤–ã‚µã‚¤ãƒˆãƒ¬ãƒ“ãƒ¥ãƒ¼è¨˜äº‹](http://www.idownloadblog.com/2014/01/10/how-to-add-a-now-playing-shortcut-to-control-center/), [GitHub](https://github.com/wakinchan/CCNowPlaying), [ã‚«ã‚¦ãƒ³ã‚¿](http://apt.thebigboss.org/stats.php?dev=kindadev)
        """
        [[params.information.list.items]]
        details = "2013 Â· TunesTweet / macOS app: iTunesã§å†ç”Ÿã—ã¦ã„ã‚‹æ›²ã‚’Shareå‡ºæ¥ã‚‹ã‚¢ãƒ—ãƒª"


        [[params.information.list]]
        title = "Papers / Web"
        [[params.information.list.items]]
        details = "2020 Â· Related [Automatically measure your clothes on a smartphone with AR](https://engineering.mercari.com/en/blog/entry/2020-06-19-150222/)"
        [[params.information.list.items]]
        details = "2017.07.20 Â· Related [SPECIAL REPORT iOSDC Japan 2017, WEB+DB PRESS Vol. 101 page 9](http://gihyo.jp/magazine/wdpress/archive/2017/vol101)"
        [[params.information.list.items]]
        details = "2015.09.18 Â· [ãƒ™ãƒªãƒˆãƒ©ãƒ³ã‚¹ã¨ãƒãƒ³ã‚ºãƒ©ãƒœã€æ±æ€¥ãƒãƒ³ã‚ºã«ã‚¯ãƒ¬ã‚¸ãƒƒãƒˆã‚«ãƒ¼ãƒ‰æƒ…å ±ã®éä¿æŒåŒ–ã¨ICã‚«ãƒ¼ãƒ‰ã«å¯¾å¿œã—ãŸPOSã‚·ã‚¹ãƒ†ãƒ ã‚’æä¾›é–‹å§‹ ï½çµŒæ¸ˆç”£æ¥­çœæ¨é€²ã®ã€Œã‚«ãƒ¼ãƒ‰å–å¼•ã«ãŠã‘ã‚‹ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£å¯¾ç­–ã®å¼·åŒ–ã«å‘ã‘ãŸå®Ÿè¡Œè¨ˆç”»ã€ã«å¯¾å¿œï½](http://www.itmedia.co.jp/enterprise/articles/1509/18/news032.html)"
        [[params.information.list.items]]
        details = "2015.09.29 Â· [ãƒ“ã‚¸ãƒã‚¹ã¨Apple ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢è‚²æˆã¨ã‚¢ãƒ—ãƒªé–‹ç™ºã®å†…è£½åŒ–ãŒå¤‰é©ã®è‚, Mac Fan 2015å¹´11æœˆå· page 194 ~ 195](https://book.mynavi.jp/macfan/content/id=43083)"
        [[params.information.list.items]]
        details = "2015.10.28 Â· [æ•°åƒå°ã® iPod Touch ç®¡ç†ã®æ‰‹é–“ã‚’é£›èºçš„ã«å‰Šæ¸›ã€æ±æ€¥ãƒãƒ³ã‚ºãŒæ¡ç”¨ã—ãŸæœ€æ–°ã®ãƒ¢ãƒã‚¤ãƒ«ç®¡ç†ã¨ã¯](http://news.mynavi.jp/kikaku/2015/10/28/001/), [äº‹ä¾‹](http://www.i3-systems.com/case.html)"
        [[params.information.list.items]]
        details = "2015.09.18 Â· [å®¢ã¨åº—ã®ã§ãã‚‹ã“ã¨ãŒèåˆï¼Ÿæ±æ€¥ãƒãƒ³ã‚ºã®iPod touchå°å…¥è¨˜](http://www.itmedia.co.jp/enterprise/articles/1509/18/news032.html)"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/wakinchan"
        title = "Github"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/wa_kinchan/"
        title = "Twitter"
        [[params.social.list]]
        icon = "fab fa-facebook-square"
        url = "//www.facebook.com/cykinda"
        title = "Facebook"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//www.linkedin.com/in/yusuke-kuroiwa-138b614b/"
        title = "LinkedIn"
        [[params.social.list]]
        icon = "fab fa-slideshare"
        url = "//www.slideshare.net/kindaiddqd"
        title = "SlideShare"
        [[params.social.list]]
        icon = "fab fa-speaker-deck"
        url = "//speakerdeck.com/wakinchan"
        title = "Speaker Deck"
        [[params.social.list]]
        icon = "fas fa-external-link-square-alt"
        url = "//qiita.com/wa_kinchan"
        title = "Qiita"

    [params.footer]
        copyright = "wakinchan"
